# version: "3.8"

services:
  db:
    build: ./docker/postgres
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: "${DB_PATH}"
    volumes:
      - data:/var/lib/postgresql/data
      - backup:/backups
      - ./${DB_VOLUME_PATH}/data:/var/lib/postgresql
      - ./${DB_VOLUME_PATH}/dumps:/tmp/dumps
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: "pg_isready -q -h db"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - ${NETWORK_NAME}
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
  s3:
    image: minio/minio
    container_name: ${COMPOSE_PROJECT_NAME}_s3
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./${S3_VOLUME_PATH}:/data
    environment:
      MINIO_ROOT_USER: ${S3_USER}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    command: server /data --console-address :9001
    networks:
      - xefferia
volumes:
  data:
  backup:
networks:
  xefferia:
    external: true
